print("╔════════════════════════╗")
print("║   PYTHON ÇALIŞMALARI   ║")
print("║1-HESAP MAKİNESİ        ║")
print("║2-OYUNLAR               ║")
print("║3-ŞEKİL ÇİZDİRME        ║")
print("║4-TAKVİM                ║")
print("║5-RİTMİK SAYMA          ║")
print("║6-NOT HESAPLAMA         ║")
print("║7-ÇARPIM TABLOSU        ║")
print("║8-BMI HESAPLAMA         ║")
print("║9-DÖVÜZ UYGULAMASI      ║")
print("║10-SICAKLIK ÇEVİRME     ║")
print("║11-ÇIKIŞ (e)            ║")
print("║    Seçimini Yap        ║")
print("╚════════════════════════╝")

print("Seçiminiz:")
